# Generated by Django 2.2 on 2020-10-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='a_message',
        ),
    ]
