# Generated by Django 2.2 on 2020-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirest_tvshow_app', '0002_auto_20201006_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
