# Generated by Django 2.2 on 2020-10-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertemp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emails_address',
            new_name='email_address',
        ),
    ]
